language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t nirbe/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true nirbe/docker-react npm run test -- --coverage
