language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t nirbe/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true nirbe/docker-react npm run test -- --coveragea

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker-react"
        env: "Dockerreact-env"
        bucket_name: "elasticbeanstalk-us-east-2-534317188233"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
